# Generated by Django 2.1.2 on 2018-10-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_name', models.CharField(max_length=200)),
                ('description', models.CharField(default='Empty!', max_length=500)),
                ('team_members', models.CharField(max_length=1000)),
                ('progress_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
