# Generated by Django 2.1.2 on 2018-10-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationalQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='nest',
            name='is_launched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nest',
            name='max_members',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='nest',
            name='num_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nest',
            name='project_type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='nest',
            name='weekly_committment_hours',
            field=models.IntegerField(default=0),
        ),
    ]
